# Generated by Django 5.0.7 on 2024-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=25)),
                ('people', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('additional_comments', models.TextField(default='If none, leave field as is', max_length=3000)),
            ],
        ),
    ]
