# Generated by Django 5.0.7 on 2024-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('None', 'None'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Engagement', 'Engagement'), ('Other', 'Other')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='seating_preferences',
            field=models.CharField(choices=[('None', 'None'), ('Indoors', 'Indoors'), ('Outdoor (Patio)', 'Outdoor (Patio)'), ('Outdoor (Sidewalk)', 'Outdoor (Sidewalk)')], default='None', max_length=20),
        ),
    ]
